name: Robot Vegano UY

on:
  schedule:
    - cron: '0 3 * * 1' # Corre todos los lunes a las 3 AM (URU)
  workflow_dispatch: # Permite darle al botón "Play" manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install firebase-admin requests

      - name: Ejecutar Robot
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python importador.py
